# Init
FROM wordpress

# Configuration
RUN echo -e "mypass\nmypass\n" | passwd
RUN apt update
RUN apt upgrade -y
RUN apt install mariadb-server -y
RUN service mysql start
ADD https://raw.githubusercontent.com/debalti/debalti-backend-create/live/wordpress-conf/wpinstall.sh /wpinstall.sh
RUN chmod 700 /wpinstall.sh && /wpinstall.sh

# Cleanup
RUN rm /wpinstall.sh

# Expose and Start Services
RUN service apache2 restart
EXPOSE 80 443
