# Init
FROM wordpress

# Configuration
RUN apt update
RUN apt upgrade -y
RUN apt install mariadb-server -y
ADD https://raw.githubusercontent.com/debalti/debalti-backend-create/live/wordpress-conf/wpinstall.sh /wpinstall.sh
RUN chmod 700 && /wpinstall.sh

# Cleanup
RUN rm /wpinstall.sh

# Expose and Start Services
RUN service apache2 restart
EXPOSE 80 443
